config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
    resources :entries, only: [:new, :create]
  end

  resources :entries, only: [:show, :edit, :update, :destroy] do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy] do
    member do
      put 'approve'
    end
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :entries, ->  {order(created_at: :DESC, id: :DESC)}, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :entry
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :comments, -> {order(created_at: :DESC, id: :DESC)}, dependent: :destroy
  belongs_to :blog

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.order(created_at: :DESC, id: :DESC).all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy, :approve]

  # POST /comments
  # POST /comments.json
  def create
    @entry = Entry.find(params[:entry_id])
    @comment = @entry.comments.new(comment_params.merge(status: 'Unapproved'))

    respond_to do |format|
      if @comment.save
        Mailer.notify_new_comment(request.original_url, @comment).deliver_later
        format.html { redirect_to entry_url(@entry), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to entry_url(@entry) }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to entry_url(@comment.entry), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /comments/1/approve
  def approve
    respond_to do |format|
      if @comment.update(status: 'Approved')
        format.html { redirect_to entry_url(@comment.entry), notice: 'Comment was approved.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :status, :entry_id)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries/1
  # GET /entries/1.json
  def show
    @comment = Comment.new
  end

  # GET /entries/new
  def new
    @blog = Blog.find(params[:blog_id])
    @entry = @blog.entries.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @blog = Blog.find(params[:blog_id])
    @entry = @blog.entries.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to blog_url(@entry.blog), notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Show', @blog
\|
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%h1 Listing blogs

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title
        %td= link_to 'Show', blog
        %td= link_to 'Edit', edit_blog_path(blog)
        %td= link_to 'Destroy', blog, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Blog', new_blog_path

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @blog.title

= link_to 'Edit', edit_blog_path(@blog)
\|
= link_to 'Back', blogs_path

= render :partial => 'entries/list'

app/views/comments/_form.html.haml
= form_for([@entry, @comment]) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/comments/_list.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th Body
      %th Status
      %th{:colspan => "3"}
  %tbody
    - @entry.comments.try(:each) do |comment|
      %tr
        %td
          - if comment.status == 'Approved'
            = simple_format(comment.body)
          - else
            = '(承認待ち)'
        %td
          - if comment.status != 'Approved'
            = link_to 'Approve', approve_comment_path(comment), :method => :put
        %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', entry_path(@comment.entry)

app/views/comments/index.html.haml
= render 'list'

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @comment.body
%p
  %b Status:
  = @comment.status
%p
  %b Entry:
  = @comment.entry_id

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', entry_path(@comment.entry)

app/views/entries/_form.html.haml
= form_for([@blog, @entry]) do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2
        = pluralize(@entry.errors.count, "error")
        prohibited this entry from being saved:
      %ul
        - @entry.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    = f.submit

app/views/entries/_list.html.haml
%h1 Listing Entries
%table
  %thead
    %tr
      %th Title
      %th Body
      %th{:colspan => "3"}
  %tbody
    - @blog.entries.try(:each) do |entry|
      %tr
        %td= entry.title
        %td= simple_format(entry.body)
        %td= link_to 'Show', entry
        %td= link_to 'Edit', edit_entry_path(entry)
        %td= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Entry', new_blog_entry_path(@blog)

app/views/entries/edit.html.haml
%h1 Editing Entry
= render 'form'
= link_to 'Show', @entry
|
= link_to 'Back', blog_path(@entry.blog_id)

app/views/entries/index.html.haml
%p#notice= notice
= render 'list'

app/views/entries/new.html.haml
%h1= "New Entry: #{@blog.title}"
= render 'form'
= link_to 'Back', blog_path(@blog)

app/views/entries/show.html.haml
= @entry.blog.title

%p#notice= notice
%p
  %strong Title:
  = @entry.title
%p
  %strong Body:
  = simple_format(@entry.body)
= link_to 'Edit', edit_entry_path(@entry)
|
= link_to 'Back', blog_path(@entry.blog)

= render :partial => 'comments/list'

%h2 New comment
= render :partial => 'comments/form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HelloRails
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield